CREATE OR REPLACE PACKAGE PCK_SUPP_CAW AS
  PROCEDURE SP_CONSULTA_FILA_ANALISE;
END PCK_SUPP_CAW;
/
CREATE OR REPLACE PACKAGE BODY PCK_SUPP_CAW AS
  PROCEDURE SP_CONSULTA_FILA_ANALISE IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Análise iniciada NEW.');
  END SP_CONSULTA_FILA_ANALISE;
END PCK_SUPP_CAW;
/
