CREATE OR REPLACE PACKAGE PCK_SUPP_PRODUTOS_SERASA AS
  PROCEDURE SP_PROCESSA_CONSULTA_SERASA;
END PCK_SUPP_PRODUTOS_SERASA;
/
CREATE OR REPLACE PACKAGE BODY PCK_SUPP_PRODUTOS_SERASA AS
  PROCEDURE SP_PROCESSA_CONSULTA_SERASA IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Gerando consulta Serasa.');
  END SP_PROCESSA_CONSULTA_SERASA;
END PCK_SUPP_PRODUTOS_SERASA;
/
