name: Liquibase Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  validate:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
      with:
        clean: false
        persist-credentials: false
      
    - name: Validate Liquibase Changelog
      run: |
        docker run --rm \
          --user $(id -u):$(id -g) \
          -v ${PWD}:/liquibase/changelog \
          -v ${PWD}/lib/ojdbc11.jar:/liquibase/lib/ojdbc11.jar \
          liquibase/liquibase:4.28.0 \
          --defaultsFile=/liquibase/changelog/liquibase.properties \
          --searchPath=/liquibase/changelog \
          validate

    - name: Update Liquibase Changelog
      run: |
        docker run --rm \
          --user $(id -u):$(id -g) \
          -v ${PWD}:/liquibase/changelog \
          -v ${PWD}/lib/ojdbc11.jar:/liquibase/lib/ojdbc11.jar \
          liquibase/liquibase:4.28.0 \
          --defaultsFile=/liquibase/changelog/liquibase.properties \
          --searchPath=/liquibase/changelog \
          update