name: Pipeline Liquibase

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Ação desejada'
        required: true
        type: choice
        options:
          - update
          - rollback
      rollbackTag:
        description: 'Tag para rollback (necessário apenas se a ação for rollback)'
        required: false
        type: string

permissions:
  contents: read
  
jobs:
  database-changes:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
      with:
        clean: false
        persist-credentials: false
      
    - name: Valida Liquibase Changelog
      id: validate
      run: |
        set -e
        echo "Iniciando validação do changelog..."
        if ! docker run --rm \
          --user $(id -u):$(id -g) \
          -v ${PWD}:/liquibase/changelog \
          -v ${PWD}:/liquibase/packages \
          -v ${PWD}/lib/ojdbc11.jar:/liquibase/lib/ojdbc11.jar \
          liquibase/liquibase:4.28.0 \
          --defaultsFile=/liquibase/liquibase.properties \
          --searchPath=/liquibase/changelog,/liquibase/packages \
          --log-level=DEBUG \
          validate; then
          echo "::error::Falha na validação do Liquibase Changelog"
          exit 1
        fi
        echo "Validação concluída com sucesso!"

    - name: Executa Ação no Banco
      if: success() 
      run: |
        if [ "${{ github.event.inputs.action }}" = "update" ]; then
          docker run --rm \
          --user $(id -u):$(id -g) \
          -v ${PWD}:/liquibase/changelog \
          -v ${PWD}:/liquibase/packages \
          -v ${PWD}/lib/ojdbc11.jar:/liquibase/lib/ojdbc11.jar \
          liquibase/liquibase:4.28.0 \
          --defaultsFile=/liquibase/liquibase.properties \
          --searchPath=/liquibase/changelog,/liquibase/packages \
          --log-level=DEBUG \
          update
        elif [ "${{ github.event.inputs.action }}" = "rollback" ]; then
          docker run --rm \
          --user $(id -u):$(id -g) \
          -v ${PWD}:/liquibase/changelog \
          -v ${PWD}:/liquibase/packages \
          -v ${PWD}/lib/ojdbc11.jar:/liquibase/lib/ojdbc11.jar \
          liquibase/liquibase:4.28.0 \
          --defaultsFile=/liquibase/liquibase.properties \
          --searchPath=/liquibase/changelog,/liquibase/packages \
          --log-level=DEBUG \
          rollback ${{ github.event.inputs.rollbackTag }}
        fi